// server/workshop/render-states.mjs
//
// Renders the machines to Markdown. The declarations are the source of truth;
// this file exists so a human can read them without reading JavaScript. Run it
// after changing any machine:  node server/workshop/render-states.mjs
import { writeFile } from 'node:fs/promises';
import { MACHINES } from './state-machines.js';

const lines = [
  '# Workshop state machines',
  '',
  '**Generated by `server/workshop/render-states.mjs` — do not edit by hand.**',
  'Change `server/workshop/state-machines.js` and re-run it.',
  '',
  'These are independent on purpose: approval, custody, work and collection are',
  'separate facts. A bike can be finished but uncollected, or approved and not',
  'started. Cross-machine rules are enforced in',
  '`tests/workshop-state-invariants.test.js`.',
  '',
  '**Rest** means nothing happens from here on its own. Some rest states have no',
  'way out at all; others are left only by a deliberate act, such as reopening a',
  'job or bringing a bike back.',
  '',
];

for (const m of MACHINES) {
  lines.push(`## ${m.name}`, '');
  lines.push(`Starts at \`${m.initial}\`. Rests at ${m.rest.map(s => `\`${s}\``).join(', ')}.`, '');
  lines.push('| From | Event | To |', '|---|---|---|');
  for (const [from, events] of Object.entries(m.transitions)) {
    for (const [event, to] of Object.entries(events)) {
      lines.push(`| \`${from}\` | \`${event}\` | \`${to}\` |`);
    }
  }
  lines.push('');
}

await writeFile(new URL('../../docs/design/workshop-states.md', import.meta.url), lines.join('\n') + '\n');
console.log(`Rendered ${MACHINES.length} machines`);
